import type { Project, InstructionFile, PromptFile, Skill, SubagentFile } from "./project.js";
import type { McpServer } from "./schema.js";

export type ArtifactType =
  "instructions" | "mcpServers" | "skills" | "prompts" | "subagents" | "hooks" | "settings";

export type Fidelity = "full" | "partial" | "unsupported";

/**
 * Where configuration lives: "project" (repo-level files) or "global"
 * (user-level files under the home directory).
 */
export type Scope = "project" | "global";

type WriteStrategyKind =
  /** File is fully owned by kata; overwritten byte-for-byte. */
  | "replace"
  /** Markdown file users may hand-edit; only the marked region is managed. */
  | "managed-region"
  /**
   * JSON file shared with the user/tool; our fragment is deep-merged over the
   * existing document (our keys win, unknown keys are preserved).
   */
  | "json-merge"
  /**
   * TOML file shared with the user/tool; same merge semantics as json-merge.
   * Note: comments in the existing file are not preserved on merge.
   */
  | "toml-merge";

export interface WriteStrategy {
  kind: WriteStrategyKind;
}

export interface EmittedFile {
  /** Path relative to the project root, or to the home dir when scope is "global". */
  relativePath: string;
  /** Defaults to "project". Global files are resolved against the home dir. */
  scope?: Scope;
  /**
   * For "replace": full file content - a Buffer for binary assets, written
   * byte-for-byte (Buffers are only valid with "replace").
   * For "managed-region": the region body (markers added on merge).
   * For "json-merge" / "toml-merge": JSON string of the fragment to merge.
   */
  content: string | Buffer;
  strategy: WriteStrategy;
}

export interface AdapterWarning {
  message: string;
  artifact?: ArtifactType;
}

export interface EmitResult {
  files: EmittedFile[];
  warnings: AdapterWarning[];
}

export interface AdapterContext {
  project: Project;
  /** Where native project-scope files are written. Same as project.rootDir. */
  projectRoot: string;
  homeDir: string;
  /**
   * Which scope this run emits for. "project" (default) emits repo-level
   * files; "global" emits the tool's user-level files (paths relative to
   * homeDir via EmittedFile.scope).
   */
  scope: Scope;
  /** The `options` bag from config.yaml for this target. */
  targetOptions: Record<string, unknown>;
}

/** Native files translated back into kata artifacts. */
export interface ImportResult {
  instructions: InstructionFile[];
  mcpServers: Record<string, McpServer>;
  prompts: PromptFile[];
  agents: SubagentFile[];
  skills: Skill[];
  warnings: AdapterWarning[];
}

export function emptyImportResult(): ImportResult {
  return { instructions: [], mcpServers: {}, prompts: [], agents: [], skills: [], warnings: [] };
}

export interface Adapter {
  /** Stable id used in config.yaml `targets`, e.g. "claude-code". */
  id: string;
  displayName: string;
  capabilities: Partial<Record<ArtifactType, Fidelity>>;
  /** Is this tool installed / initialized for this user or project? */
  detect(context: AdapterContext): Promise<boolean>;
  /** Kata artifacts -> native files. Pure: must not touch the filesystem. */
  emit(context: AdapterContext): Promise<EmitResult>;
  /**
   * Native files -> kata artifacts, for onboarding existing setups.
   * Reads the filesystem (project scope only). Content generated by kata
   * itself (managed regions, kata-owned files) must be excluded.
   */
  import?(context: AdapterContext): Promise<ImportResult>;
}

export class AdapterRegistry {
  private adapters = new Map<string, Adapter>();

  register(adapter: Adapter): void {
    if (this.adapters.has(adapter.id)) {
      throw new Error(`Adapter "${adapter.id}" is already registered`);
    }
    this.adapters.set(adapter.id, adapter);
  }

  get(id: string): Adapter | undefined {
    return this.adapters.get(id);
  }

  all(): Adapter[] {
    return [...this.adapters.values()];
  }
}
